<div class="heading"> 
        <h2>FEED THE PEOPLE</h2>
    </div>

    <br>
    <br>

<body>
        <!-- Describe What the charity/movement does -->
        <div>
            <h4 class="text">
                Our mission is to support and uplift vulnerable groups in society,
                ensuring that their fundamental needs are met and their human rights are upheld.
                Through compassion, advocacy, and direct assistance, we strive to create a world where no one is left behind.
                Join us in making a difference—because everyone deserves dignity, security, and hope.
            </h4>
            
            <br>
            <br>
            <br>

            <div class="slideshow-container">
                <img class="slide" src="charityphotos/img1.jpeg" alt="Slide 1">
                <img class="slide" src="charityphotos/img2.png" alt="Slide 2">
            </div>

            <h4 class="text">
            </h4>
        </div>

        <br>
        <br>
        <br>

        <!-- Add QR Code Image that takes people directly to payments -->
        <div class="cen">
            <img src="" alt="">
        </div>

        <!-- Add API for secure payments -->
        <div class="cen">
            <form action="index.php?action=processPayment" method="POST">
                <button type="submit" class="center-button">SECURE DONATION</button>
            </form>
        </div>

        <script src="slideshow.js"></script>
               
    </body>