<div class="heading"> 
        <h2>FEED THE PEOPLE</h2>
    </div>

    <br>
    <br>

<body>
        <!-- Describe What the charity/movement does -->
        <div>
            <h4 class="text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                Integer nec odio. Praesent libero. Sed cursus ante dapibus diam.
                Sed nisi. Nulla quis sem at nibh elementum imperdiet.
                Duis sagittis ipsum. Praesent mauris.
                Fusce nec tellus sed augue semper porta.
                Mauris massa. Vestibulum lacinia arcu eget nulla.
                Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
            </h4>
            
            <br>
            <br>
            <br>

            

            <h4 class="text">
                Curabitur sodales ligula in libero.
                Sed dignissim lacinia nunc.
                Curabitur tortor. 
                Pellentesque nibh. 
                Aenean quam. In scelerisque sem at dolor. Maecenas mattis. 
                Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor.
                Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. 
                Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. 
                Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh.
            </h4>
        </div>

        <br>
        <br>
        <br>

        <!-- Add QR Code Image that takes people directly to payments -->
        <div class="cen">
            <img src="" alt="">
        </div>

        <!-- Add API for secure payments -->
        <div class="cen">
            <button class="center-button">SECURE DONATION</button>
        </div>


               
    </body>