<div class="heading"> 
        <h2>FEED THE PEOPLE</h2>
    </div>

    <br>
    <br>

<body>
        <!-- Describe What the charity/movement does -->
        <div>
            <h4 class="text">
                Thank you for your donation and support!
            </h4>
            
            <br>
            <br>
            <br>

        </div>

        <br>
        <br>
        <br>


        <!-- return to index -->
        <div class="cen">
            <form action="paymentSuccess.php?action=index" method="POST">
                <button type="submit" class="center-button">BACK HOME</button>
            </form>
        </div>

               
    </body>